# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
swagger.json:
  spec:
    - '#/paths/~1session~1openid~1auth/get/parameters/0'
    - '#/paths/~1session~1openid~1callback/get/parameters/0'
  operation-operationId:
    - '#/paths/~1session~1openid~1callback/get/operationId'
    - '#/paths/~1users/get/operationId'
    - '#/paths/~1users/post/operationId'
    - '#/paths/~1users~1{id}/put/operationId'
    - '#/paths/~1users~1{id}/delete/operationId'
    - '#/paths/~1notifications/get/operationId'
    - '#/paths/~1notifications/post/operationId'
    - '#/paths/~1notifications~1{id}/put/operationId'
    - '#/paths/~1notifications~1{id}/delete/operationId'
    - '#/paths/~1notifications~1types/get/operationId'
    - '#/paths/~1notifications~1test/post/operationId'
    - '#/paths/~1geofences/get/operationId'
    - '#/paths/~1geofences/post/operationId'
    - '#/paths/~1geofences~1{id}/put/operationId'
    - '#/paths/~1geofences~1{id}/delete/operationId'
    - '#/paths/~1events~1{id}/get/operationId'
    - '#/paths/~1reports~1route/get/operationId'
    - '#/paths/~1reports~1events/get/operationId'
    - '#/paths/~1reports~1summary/get/operationId'
    - '#/paths/~1reports~1trips/get/operationId'
    - '#/paths/~1reports~1stops/get/operationId'
    - '#/paths/~1statistics/get/operationId'
    - '#/paths/~1calendars/get/operationId'
    - '#/paths/~1calendars/post/operationId'
    - '#/paths/~1calendars~1{id}/put/operationId'
    - '#/paths/~1calendars~1{id}/delete/operationId'
    - '#/paths/~1attributes~1computed/get/operationId'
    - '#/paths/~1attributes~1computed/post/operationId'
    - '#/paths/~1attributes~1computed~1{id}/put/operationId'
    - '#/paths/~1attributes~1computed~1{id}/delete/operationId'
    - '#/paths/~1drivers/get/operationId'
    - '#/paths/~1drivers/post/operationId'
    - '#/paths/~1drivers~1{id}/put/operationId'
    - '#/paths/~1drivers~1{id}/delete/operationId'
    - '#/paths/~1maintenance/get/operationId'
    - '#/paths/~1maintenance/post/operationId'
    - '#/paths/~1maintenance~1{id}/put/operationId'
    - '#/paths/~1maintenance~1{id}/delete/operationId'
  operation-summary:
    - '#/paths/~1events~1{id}/get/summary'
  no-unused-components:
    - '#/components/parameters/entityId'
    - '#/components/parameters/all'
    - '#/components/parameters/refresh'
    - '#/components/parameters/userId'
    - '#/components/parameters/deviceId'
    - '#/components/parameters/groupId'
    - '#/components/parameters/deviceIdArray'
    - '#/components/parameters/groupIdArray'
    - '#/components/parameters/fromTime'
    - '#/components/parameters/toTime'
    - '#/components/requestBodies/Device'
    - '#/components/requestBodies/Permission'
    - '#/components/requestBodies/Group'
    - '#/components/requestBodies/User'
    - '#/components/requestBodies/Geofence'
    - '#/components/requestBodies/Calendar'
    - '#/components/requestBodies/Attribute'
    - '#/components/requestBodies/Driver'
    - '#/components/requestBodies/Command'
    - '#/components/requestBodies/Notification'
    - '#/components/requestBodies/Maintenance'
